-- AlterTable
ALTER TABLE "Balance" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ExpenseParticipant" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GroupBalance" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
